---
# NOTE: use either this pre-defined 'network_interface' (IP of octalfutures.com domainname)
# or grp and vpc_subnet

- name: install and start unihood instance
  hosts: localhost
  gather_facts: false
  vars:
    image: ami-9398d3e0
    instance_type: t2.micro
    key_name: aws-dc
    region: eu-west-1
    network_interface: eni-9bbc8bfc
    group_id: sg-b40557d3 
    vpc_subnet_id: subnet-56f2200e 

  tasks:
    - name: Launch UniHood instance
      ec2:
        group_id: "{{ group_id }}"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        #assign_public_ip: yes
        #network_interface: "{{network_interface}}"
        image: "{{ image }}"
        instance_type: "{{ instance_type }}"
        key_name: "{{ key_name }}"
        wait: True
        region: "{{ region }}"
        exact_count: 1
        count_tag:
            uniclass: unihoodsvr
        instance_tags:
            uniclass: unihoodsvr
      register: ec2_launch_result

    - name: Add new instance(s) to host group
      add_host: hostname={{ item.public_ip }} groupname=launched
      with_items: "{{ ec2_launch_result.instances }}"

    - name: Wait for any new SSHds to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: "{{ ec2_launch_result.instances }}"

# - name: Configure UniHood instance
#   hosts: unihoods
#   become: True
#   gather_facts: True
#   roles:
#     - unihoodsvr
